"""Added number_of_children colums to Resident

Revision ID: 60ff84fac7da
Revises: 2328d1a24d2b
Create Date: 2025-06-06 22:16:06.881139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ff84fac7da'
down_revision: Union[str, None] = '2328d1a24d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residents', sa.Column('number_of_children', sa.Integer(), nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residents', 'number_of_children')
    # ### end Alembic commands ###
