"""email to allowed list

Revision ID: c0b9e6b3c764
Revises: 877364011d07
Create Date: 2025-03-14 03:27:02.234434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b9e6b3c764'
down_revision: Union[str, None] = '877364011d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowList', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_allowList_email'), 'allowList', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allowList_email'), table_name='allowList')
    op.drop_column('allowList', 'email')
    # ### end Alembic commands ###
